baseURL = "https://regisrouyard.com"
languageCode = "en-us"
title = "Régis ROUYARD Resume"
theme = "resume"
[params]
    firstName = "Régis"
    lastName = "Rouyard"
    address = "81 rue charles infroit, 94400 VITRY-SUR-SEINE"
    phone = "(+33)06 7304 1261"
    contactNote = "Backend Web Developer"
    profileImage = "img/rr.png"
    email = "regis.rouyard@gmail.com"
    description = "Backend Web Developer"
    favicon = "img/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true


    showQr = false
    showBio = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/regisrouyard/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ReRou/"
    
[[params.handles]]
    name = "Certificate"
    link = "https://directory.opquast.com/fr/certificat/16JL9K/"

license = "MIT"
licenselink = "https://raw.githubusercontent.com/ReRou/cv/master/LICENSE"
description = "Personal resume with social handles, skills inventory and work history. Ported from StartBootstrap 'Resume' theme"
homepage = "https://regisrouyard.com/"
tags = ["resume","responsive"]
